config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :places, only: [ :index, :create, :edit, :show, :update, :new ] do
    resources :bookings, only: [ :index, :create, :edit, :show, :update ]
  end

  get "/dashboard", to: "dashboard#index"
  get "/bookings/:id/accept", to: "bookings#accept", as: :accept_bookings
  get "/bookings/:id/decline", to: "bookings#decline", as: :decline_bookings



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :date, uniqueness: { scope: :place }
end

app/models/place.rb
class Place < ApplicationRecord
  include PgSearch::Model
  has_many :bookings
  has_many_attached :photos
  # validates :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :global_search,
    against: [ :address, :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # [...]
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit

    # Pundit: white-list approach.
    # after_action :verify_authorized, except: :index, unless: :skip_pundit?
    # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
    end

    private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :accept, :decline]


  def index
    @bookings = Booking.all
    @places = Place.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @place = Place.find(params[:place_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @place = Place.find(params[:place_id])
    @booking = Booking.new
    @booking.user = current_user
    @booking.place = @place
    @booking.date = Date.new(params[:booking][:"date(1i)"].to_i, params[:booking][:"date(2i)"].to_i, params[:booking][:"date(3i)"].to_i)
    @booking.confirmed = nil
    authorize @booking

    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @place = @booking.place
    @booking.destroy
    redirect_to bookings_path(@place)
  end

  def accept
    authorize @booking
    @booking.update(confirmed: true)
    if @booking.save
      redirect_to dashboard_path, notice: "You have accepted booking of place # #{@booking.place.name}"
    end
  end

  def decline
    authorize @booking
    @booking.update(confirmed: false)
    if @booking.save
      redirect_to dashboard_path, alert: "You have declined booking of flat # #{@booking.place.name}"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:confirmed, :place_id, :date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
    @places = Place.where(user_id: current_user.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

  def home
    @places = Place.all.sample(12)
  end



end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    skip_authorization
    # @places = Place.all
    # @places = policy_scope(Place)
    if params[:query].present?
      @places = policy_scope(Place).global_search(params[:query])
    else
      @places = policy_scope(Place).all
    end
  end

  def show
    @booking = Booking.new
    @markers = 
      [{
        lat: @place.latitude,
        lng: @place.longitude
      }]
  end

  # def accept
  #   raise
  #   @place = Place.find(params[:place_id])
  #   if @place.user_id == current_user.id
  #     @booking.confirmed = true
  #     authorize @booking
  #     # owner's dashboard
  #     redirect_to dashboard_path, notice: "You have accepted booking of place # #{@place.name}"
  #   end
  # end

  # def decline
  #   @place = Place.find(params[:flat_id])
  #   if @place.user_id == current_user.id
  #     @booking.confirmed = false
  #     authorize @booking
  #     redirect_to dashboard_path, alert: "You have declined booking of flat # #{@place.name}"
  #   end
  # end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    authorize @place

    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @place.update(place_params)
    redirect_to place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to places_path
  end

  private

  def set_place
    @place = Place.find(params[:id])
    authorize @place
  end

  def place_params
    params.require(:place).permit(:name, :address, :description, :price, photos:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<%= simple_form_for [@place, @booking] do |f| %>
  <%= f.input :date %>
  <%= f.submit "Book the flat", class: "btn btn-primary" %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit a Place</h1>

<%= render 'form' %>

app/views/bookings/index.html.erb
<h1>Minhas reservas</h1>

<div>
<% @bookings.each do |booking| %>
  <% if booking.user_id == current_user.id %>
    <% if booking.confirmed.nil?  %>
      <% status = "Pendente"  %>
    <% else %>
      <% status = booking.confirmed ? "Confirmado" : "Recusado"  %>
    <% end %>
    <li><%= booking.place.name %> / <%= booking.user_id %> / <%= booking.date %> / <%= status %></li>
  <% end %>
<% end %>
</div>

<h1>Minhas casas</h1>

<div>
<% @bookings.each do |booking| %>
  <% @places.each do |place| %>
    <% if place.user_id == current_user.id %>
      <% if place.id == booking.place_id %>
        <% if booking.confirmed.nil?  %>
          <% status = "Pendente"  %>
        <% else %>
          <% status = booking.confirmed ? "Confirmado" : "Recusado"  %>
        <% end %>
        <li><%= booking.place.name %> / Host: <%= place.user_id %> / Guest: <%= booking.user_id %> / <%= booking.date %> / <%= status %></li>
      <% end %>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/bookings/new.html.erb
<h1>Criando booking</h1>

<%= render 'new' %>

app/views/bookings/show.html.erb
<h1>Info about Booking</h1>

<p>Name: <%= @booking.place.name %></p>
<p>Date: <%= @booking.date%></p>
<p>Status: Pending</p>



<!-- Não use tag a no rails, sempre use link_to -->
<!-- <a href="/bookings">All bookings</a> -->

<p>
  <%= link_to 'HOME', root_path %>
</p>

app/views/dashboard/index.html.erb
<h2>Olá, <%= current_user.email %></h2>

<h1>Minhas reservas</h1>

<ul>
  <% @bookings.each do |booking| %>

      <% if booking.confirmed.nil?  %>
        <% status = "Pendente"  %>
      <% else %>
        <% status = booking.confirmed ? "Confirmado" : "Recusado"  %>
      <% end %>
      <li><%= booking.place.name %> / <%= booking.user_id %> / <%= booking.date %> / <%= status %></li>
    <% end %>
</ul>

<h1>Minhas casas</h1>

<ul>

    <% @places.each do |place| %>
      <% place.bookings.each do |booking| %>
        <% if booking.confirmed.nil?  %>
            <% status = "Pendente"  %>
          <% else %>
            <% status = booking.confirmed ? "Confirmado" : "Recusado"  %>
          <% end %>
          <li><%= booking.place.name %> / Host: <%= place.user_id %> / Guest: <%= booking.user_id %> /
            <%= booking.date %> / <%= status %>
            <%= link_to "Accept", accept_bookings_path(booking) %>
            <%= link_to "Decline", decline_bookings_path(booking) %>
            </li>
        <% end %>
      <% end %>


</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <%= link_to root_path,  class: "navbar-brand" do %>

        <%= image_tag "https://w7.pngwing.com/pngs/501/253/png-transparent-freight-bicycle-cycling-computer-icons-ikonlar-angle-text-logo.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            Olá<%= user_signed_in? ? " #{current_user.name}" : "!" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user and current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://static.thenounproject.com/png/2643420-200.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">


              <% if current_user %>
                <%= link_to "Torne-se um anfitrião", new_place_path, class: "dropdown-item" %>
                <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                <%= link_to "Sair", destroy_user_session_path, class: "dropdown-item", method: :delete%>
              <% else %>
                <%= link_to "Login", user_session_path, class: "dropdown-item" %>
                <%= link_to "Cadastre-se", new_user_registration_path, class: "dropdown-item" %>
              <% end %>

            </div>
          </li>
        </ul>
      </div>
    </div>



<div>
    <%= yield %>
</div>

    <div class="footer">
      <div class="footer-links">

        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>

      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>

  </body>


</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.bikemagazine.com.br/wp-content/uploads/2012/02/primeira-bike1.jpg);">
  <div class="container col-6">
    <div class="search-form-control form-group">
      <%= form_tag places_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Encontre um lugar"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
      <% end %>
    </div>
    <h1>Airbnbike <strong></strong><strong></strong></h1>
    <p>Encontre onde passar a noite durante a sua jornada.</p>
    <%= link_to "Veja todos os locais", places_path, class: "btn btn-flat" %>
  </div>
</div>

<div class='container'>
  <div class='container'>
    <div class="cards">
      <% @places.each do |place| %>
        <%= link_to place_path(place) do %>
          <div class="card-trip">
          <% if place.photos.first.present? %>
            <%= cl_image_tag place.photos.first.key, crop: :fill %>
          <% else %>
            <img src= 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg' />
          <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= place.name %></h2>
            <p><%= place.description %></p>
          </div>
        <h2 class="card-trip-pricing">$ <%= place.price.to_i %> / noite</h2>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>
 </div>
</div>

app/views/places/_form.html.erb
<div class="container mt-3">
  <%= simple_form_for(@place) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }%>
    <%= f.input :available %>
    <%= f.input :capacity %>
    <%= f.submit class: "btn btn-ghost" %>
  <% end %>
</div>

app/views/places/edit.html.erb
<div class="container col-3">
  <h1>Edite sua Acomodação</h1>
</div>

<div class="container col-3"
  <%= render 'form' %>
</div>

app/views/places/index.html.erb
<div class='container'>
  <div class="cards">
    <% @places.each do |place| %>
      <%= link_to place_path(place) do %>

      <div class="card-trip">
      <% if place.photos.first.present? %>
        <%= cl_image_tag place.photos.first.key, crop: :fill %>
      <% else %>
       <img src= 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg' />
      <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= place.name %></h2>
            <p><%= place.description %></p>
          </div>
          <h2 class="card-trip-pricing">$ <%= place.price.to_i %> / noite</h2>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<div class="container col-3">
  <h1>Cadastre sua acomodação</h1>
</div>

<div class="container col-3">
  <%= render 'form' %>
</div>

app/views/places/show.html.erb
<div class="container">
  <%= link_to "Voltar", root_path, class: "btn btn-light"%>
</div>

<div class="mx-auto" style="width: 900px;">
<div class="d-flex justify-content-center">
  <p><%= @place.name %></p>
</div>
<div class="d-flex justify-content-center">
  <p><%= @place.address %></p>
</div>
<div id="demo" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @place.photos.each_with_index do |photo, index|  %>
<!--         <% background = @place.photos.attached? ? cl_image_path(@place.photos.first.key) : 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png'%>
 -->    <div class="carousel-item banner_show <%= index == 0 ? 'active' : '' %>" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(photo.key) %>);">

        </div>
      <% end %>


    </div>
    <a class="carousel-control-prev" href="#demo" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#demo" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class='container mt-3'>
    <div class="d-flex justify-content-between" >
      <p><%= @place.description %></p>
    </div>
  
    <div class="d-flex justify-content-between">
      <div class= 'preço'>
        <h2> R$ <%= @place.price %> / noite </h2>  
      </div>
    </div>
   
    <div id="map"
      style="width: 600px; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>


<% unless current_user.id == @place.user_id %>
  <%= render 'bookings/new' %>
  <% else %>
    <% if policy(@place).update? %>
      <%= link_to "Update place", edit_place_path(@place) %>
    <% end %>
<% end %>


 



<!-- Não use tag a no rails, sempre use link_to -->
<!-- <a href="/places">All places</a> -->

<!-- <p>
  <%= link_to 'All places', places_path %>
</p>

<p>
  <%= link_to 'Edit this place', edit_place_path(@place) %>
</p>

<p>
  <%= link_to 'Remove this place', place_path(@place), method: :delete, data: { confirm: 'Are you Sure?' } %>
</p>

<p>
  <%= link_to 'HOME', root_path %>
</p>
 -->